<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

// Create shortcuts to some parameters.
$params  = $this->item->params;
$urls    = json_decode($this->item->urls);
$canEdit = $params->get('access-edit');
$user    = JFactory::getUser();
$info    = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
JHtml::_('behavior.caption');

$currentDate       = JFactory::getDate()->format('Y-m-d H:i:s');
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isExpired         = $this->item->publish_down < $currentDate && $this->item->publish_down !== JFactory::getDbo()->getNullDate();

$app  = JFactory::getApplication();

$menu = $app->getMenu();
$active = $menu->getActive();

$pageparams = $menu->getParams( $active->id );
$pageclass = $pageparams->get( 'pageclass_sfx' );

$lang = JFactory::getLanguage();
$languages = JLanguageHelper::getLanguages('lang_code');
$languageCode = $languages[ $lang->getTag() ]->sef;

foreach ($this->item->jcfields as $field) :
    $fieldsValue[$field->id] = $field->value;
    $fieldsValue[$field->name] = $field->value;
    $fieldsRawValue[$field->name] = $field->rawvalue;
endforeach;

?>
<div class="uk-card uk-card-default uk-border-rounded uk-overflow-hidden uk-box-shadow-small item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
	<?php // Todo Not that elegant would be nice to group the params ?>
	<?php $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date') || $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam); ?>

	<?php if (!$useDefList && $this->print) : ?>
		<div id="pop-print" class="btn hidden-print">
			<?php echo JHtml::_('icon.print_screen', $this->item, $params); ?>
		</div>
	<?php endif; ?>

	<?php if (!$this->print) : ?>
		<?php if ($canEdit || $params->get('show_print_icon') || $params->get('show_email_icon')) : ?>
			<?php echo JLayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item, 'print' => false)); ?>
		<?php endif; ?>
	<?php else : ?>
		<?php if ($useDefList) : ?>
			<div id="pop-print" class="btn hidden-print">
				<?php echo JHtml::_('icon.print_screen', $this->item, $params); ?>
			</div>
		<?php endif; ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
	<?php echo $this->item->event->afterDisplayTitle; ?>

	<?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
		<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
		<?php /* echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); */ ?>
	<?php endif; ?>

	<?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>

		<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
	<?php /* echo $this->item->event->beforeDisplayContent; */ ?>

	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position') == '0' && empty($urls->urls_position)))
		|| (empty($urls->urls_position) && (!$params->get('urls_position')))) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php if ($params->get('access-view')) : ?>
	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) :
		echo $this->item->pagination;
	endif;
	?>
	<?php if (isset ($this->item->toc)) :
		echo $this->item->toc;
	endif; ?>

        <?php if ($this->params->get('show_page_heading')) : ?>
            <div class="page-header">
                <h1><?php echo $this->escape($this->params->get('page_heading')); ?></h1>
            </div>
        <?php endif;
        if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative)
        {
            echo $this->item->pagination;
        }
        ?>

    <section class="uk-position-relative">
        <?php echo JLayoutHelper::render('joomla.content.full_image', $this->item); ?>
        <?php if ($params->get('show_title')) : ?>
            <div class="page-header uk-position-bottom aboutPageTitle">
                <h2 itemprop="headline" class="uk-text-center uk-margin-remove uk-text-accent uk-h1 font">
                    <?php echo $this->escape($this->item->title); ?>
                </h2>
                <?php if ($this->item->state == 0) : ?>
                    <span class="label label-warning"><?php echo JText::_('JUNPUBLISHED'); ?></span>
                <?php endif; ?>
                <?php if ($isNotPublishedYet) : ?>
                    <span class="label label-warning"><?php echo JText::_('JNOTPUBLISHEDYET'); ?></span>
                <?php endif; ?>
                <?php if ($isExpired) : ?>
                    <span class="label label-warning"><?php echo JText::_('JEXPIRED'); ?></span>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </section>


    <div class="uk-padding">
        <section<?php if (!empty($fieldsValue['certificates'])) { ?> class="uk-margin-large-bottom" <?php } ?>>
            <div itemprop="articleBody" class="uk-text-justify uk-text-secondary uk-text-small font f500"><?php echo $this->item->text; ?></div>
        </section>
        <?php if (!empty($fieldsValue['certificates'])) { ?>
            <section<?php if (!empty($fieldsValue['clients'])) { ?> class="uk-margin-large-bottom" <?php } ?>>
                <?php if (!empty($fieldsValue['certificatestitle'])) { ?>
                    <h3 class="uk-text-center uk-text-accent uk-h4 uk-margin-small-bottom f600 font"><?php echo $fieldsValue['certificatestitle']; ?></h3>
                <?php } ?>
                <?php if (!empty($fieldsValue['certificatessubtitle'])) { ?>
                    <p class="uk-text-center uk-text-secondary uk-margin-remove-top uk-margin-medium-bottom uk-text-small f500 font"><?php echo $fieldsValue['certificatessubtitle']; ?></p>
                <?php } ?>
                <div class="uk-margin-top">
                    <?php $certificates = explode('<br>', $fieldsValue['certificates']); ?>
                    <div data-uk-slider="velocity: 3; autoplay: true; autoplay-interval: 2200;">
                        <div class="uk-position-relative">
                            <div class="uk-slider-items uk-child-width-1-2 uk-child-width-1-6@m uk-grid-medium" data-uk-grid data-uk-lightbox="animation: slide">
                                <?php for ( $i=0; $i < count($certificates)-1; $i++ ) { ?>
                                    <?php $certificate = explode(",", $certificates[$i]); ?>
                                    <div>
                                        <div class="uk-box-shadow-small uk-border-rounded uk-overflow-hidden">
                                            <a class="uk-display-block uk-position-relative uk-transition-toggle" href="<?php echo $certificate[1]; ?>" data-caption="<?php echo $certificate[0]; ?>">
                                                <img src="<?php echo $certificate[1]; ?>" alt="<?php echo $certificate[0]; ?>">
                                                <div class="uk-text-white uk-transition-fade uk-position-cover uk-position-small uk-overlay uk-overlay-primary uk-flex uk-flex-center uk-flex-middle uk-margin-remove">
                                                    <img src="<?php echo JURI::base().'images/sprite.svg#expand'; ?>" width="32" height="32" data-uk-svg>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                        <ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin-medium-top"></ul>
                    </div>
                </div>
            </section>
        <?php } ?>
        <?php if (!empty($fieldsValue['clients'])) { ?>
            <section<?php if ($fieldsRawValue['catalogue']) { ?> class="uk-margin-large-bottom" <?php } ?>>
                <?php if (!empty($fieldsValue['clientstitle'])) { ?>
                    <h3 class="uk-text-center uk-text-accent uk-h4 uk-margin-small-bottom f600 font"><?php echo $fieldsValue['clientstitle']; ?></h3>
                <?php } ?>
                <?php if (!empty($fieldsValue['clientssubtitle'])) { ?>
                    <p class="uk-text-center uk-text-secondary uk-margin-remove-top uk-margin-medium-bottom uk-text-small f500 font"><?php echo $fieldsValue['clientssubtitle']; ?></p>
                <?php } ?>
                <div class="uk-margin-top">
                    <?php $clients = explode('<br>', $fieldsValue['clients']); ?>
                    <div data-uk-slider="velocity: 3; autoplay: true; autoplay-interval: 1500;">
                        <div class="uk-position-relative">
                            <div class="uk-child-width-1-2 uk-child-width-1-6@m uk-slider-items" data-uk-grid>
                                <?php for ( $i=0; $i < count($clients)-1; $i++ ) { ?>
                                    <?php $client = explode(",", $clients[$i]); ?>
                                    <div>
                                        <a href="<?php echo $client[2]; ?>" target="_blank" class="uk-flex uk-flex-center uk-flex-middle uk-height-1-1" data-caption="<?php echo $client[0]; ?>" data-uk-tooltip="title: <?php echo $client[0]; ?>; offset: 20;"><img src="<?php echo $client[1]; ?>" alt="<?php echo $client[0]; ?>"></a>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                        <ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin-medium-top"></ul>
                    </div>
                </div>
            </section>
        <?php } ?>
        <?php if ($fieldsRawValue['catalogue']) { ?>
            <section>
                <div class="uk-padding uk-background-muted uk-border-rounded">
                    <div>
                        <?php if (!empty($fieldsValue['cataloguetitle'])) { ?>
                            <h3 class="uk-text-center uk-text-accent uk-h4 uk-margin-medium-bottom f600 font"><?php echo $fieldsValue['cataloguetitle']; ?></h3>
                        <?php } ?>
                        <div class="uk-child-width-1-1 uk-child-width-1-3@m uk-grid-small" data-uk-grid>
                            <div>
                                <a href="#" class="uk-button uk-button-large uk-button-success uk-border-rounded uk-width-1-1 uk-box-shadow-small uk-text-zero uk-flex uk-flex-center uk-flex-middle">
                                    <span><img src="<?php echo JURI::base().'images/sprite.svg#home'; ?>" width="24" height="24" data-uk-svg></span>
                                    <span class="uk-text-small uk-margin-right font f500">کاتالوگ اتصالات</span>
                                </a>
                            </div>
                            <div>
                                <a href="#" class="uk-button uk-button-large uk-button-success uk-border-rounded uk-width-1-1 uk-box-shadow-small uk-text-zero uk-flex uk-flex-center uk-flex-middle">
                                    <span><img src="<?php echo JURI::base().'images/sprite.svg#home'; ?>" width="24" height="24" data-uk-svg></span>
                                    <span class="uk-text-small uk-margin-right font f500">کاتالوگ اتصالات</span>
                                </a>
                            </div>
                            <div>
                                <a href="#" class="uk-button uk-button-large uk-button-success uk-border-rounded uk-width-1-1 uk-box-shadow-small uk-text-zero uk-flex uk-flex-center uk-flex-middle">
                                    <span><img src="<?php echo JURI::base().'images/sprite.svg#home'; ?>" width="24" height="24" data-uk-svg></span>
                                    <span class="uk-text-small uk-margin-right font f500">کاتالوگ اتصالات</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        <?php } ?>
    </div>

	<?php if ($info == 1 || $info == 2) : ?>
		<?php if ($useDefList) : ?>
				<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
			<?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
		<?php endif; ?>
		<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
			<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
			<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
		<?php endif; ?>
	<?php endif; ?>

	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && !$this->item->paginationrelative) :
		echo $this->item->pagination;
	?>
	<?php endif; ?>
	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '1')) || ($params->get('urls_position') == '1'))) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php // Optional teaser intro text for guests ?>
	<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>
	<?php echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>
	<?php echo JHtml::_('content.prepare', $this->item->introtext); ?>
	<?php // Optional link to let them register to see the whole article. ?>
	<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
	<?php $menu = JFactory::getApplication()->getMenu(); ?>
	<?php $active = $menu->getActive(); ?>
	<?php $itemId = $active->id; ?>
	<?php $link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
	<?php $link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
	<p class="readmore">
		<a href="<?php echo $link; ?>" class="register">
			<?php if ($params->get('alternative_readmore', '') === '') : ?>
				<?php echo JText::_('COM_CONTENT_REGISTER_TO_READ_MORE'); ?>
			<?php else : ?>
				<?php echo $params->get('alternative_readmore'); ?>
				<?php if ($params->get('show_readmore_title', 0) != 0) : ?>
					<?php echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit')); ?>
				<?php endif; ?>
			<?php endif; ?>
		</a>
	</p>
	<?php endif; ?>
	<?php endif; ?>
	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && $this->item->paginationrelative) :
		echo $this->item->pagination;
	?>
	<?php endif; ?>
	<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
	<?php echo $this->item->event->afterDisplayContent; ?>
</div>
